### ISSUE TITLE
ThinkPHP\FW1 does not work

### ISSUE THREAD

**Issue by jelly0930** [ambionics/phpggc#113]
the attribute query of the class think\model\relation\HasMany is not set

![image](https://user-images.githubusercontent.com/37065209/147541483-e3dd751e-7304-4305-b98c-606e591a71f8.png)

and the attribute query  is  protected in ThinkPHP

I made the following changes to make it work properly

![image](https://user-images.githubusercontent.com/37065209/147541815-104eec91-7c86-4538-81d7-66e9864c9af1.png)

**Comment by cfreal** [comment]
Hello, what version of ThinkPHP are you targeting ?

**Comment by jelly0930** [comment]
My targeting is ThinkPHP 5.0.24, and the phpggc's chain.php says it works in 5.0.4-5.0.24
![image](https://user-images.githubusercontent.com/37065209/147556405-830ece0d-7239-4952-8b44-4f75677fa869.png)

**Comment by cfreal** [comment]
Hello,

Ok you are very right. Patching.

Thanks, jelly !
