### ISSUE TITLE
ThinkPHP\RCE1 does not work

### ISSUE THREAD

**Issue by jelly0930** [ambionics/phpggc#114]
There is an capitalized word in phpggc ThinkPHP\RCE1：Smi1e

![image](https://user-images.githubusercontent.com/37065209/147548874-8fa41af7-4714-4f86-97f5-7b5aa496e967.png)

But in the process of working, the word Smi1e will be converted to lowercase

![image](https://user-images.githubusercontent.com/37065209/147549138-4f32b6e6-69d7-4632-985f-c55546c50454.png)

As a result, the first lowercase word cannot be found in the array

I think the simplest and most effective way to improve is to lowercase all smi1e words

**Comment by cfreal** [comment]
Hello, what version of ThinkPHP are you targeting ?

**Comment by jelly0930** [comment]
My local test environment is ThinkPHP 5.1.41

**Comment by cfreal** [comment]
Hello jelly,

Again, you are right. Patching as well.
