### ISSUE TITLE
Guzzle chain still present

### ISSUE THREAD

**Issue by alessiogiorgianni** [ambionics/phpggc#147]
It seems that Guzzle/FW1 still exists in Guzzle versions > 6.3.3, for example in 6.5.8 version below.

https://api.github.com/repos/guzzle/guzzle/zipball/a52f0440530b54fa079ce76e8c5d196a42cad981

**Comment by cfreal** [comment]
Hello, I have updated the version for Guzzle/FW1. It works for the newest version as well.
