### ISSUE TITLE
Regarding the phar.readonly issue

### ISSUE THREAD

**Issue by CaledoniaProject** [ambionics/phpggc#161]
I think the shebang in phpggc script should be changed to `#!/usr/bin/env php -d phar.readonly=0`, what do you think?

**Comment by cfreal** [comment]
Hello CaledoniaProject,

That's an excellent idea, I didn't even think about it!

Want to PR it ?

Charles

**Comment by CaledoniaProject** [comment]
Sure, just created the PR https://github.com/ambionics/phpggc/pull/162
