### ISSUE TITLE
phpggc times out

### ISSUE THREAD

**Issue by ShutdownRepo** [ambionics/phpggc#163]
Running `/path/to/phpggc` now times out since https://github.com/ambionics/phpggc/commit/08dc8970080040a9c977395e58147e1cc10c57f7, probably because the OS doesn't understand the sheband.
Tested on Debian 12 AMD64 and ARM64. Reverting the referred commit works.
Running `php -d phar.readonly=0 /opt/tools/phpggc/phpggc` works of course. This is only a shebang format issue

**Comment by nikaiw** [comment]
ah raced by @swapgs 

this is however not portable and works from coreutils 8.30 according to this [stackoverflow](https://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-for-awk-with-a-shebang-i-e)

**Comment by ShutdownRepo** [comment]
We're good 👍
