### ISSUE TITLE
How to utilize the WordPress rec pop chain

### ISSUE THREAD

**Issue by yuedinga** [ambionics/phpggc#179]
I have browsed through many articles online and cannot find the point at which the WordPress WordPress/RCE2 chain should be utilized. Please let me know

**Comment by cfreal** [comment]
Hello yuedinga, 

I don't understand. What do you mean by "the point at which" ? You can generate it as you do for other chains.

**Comment by yuedinga** [comment]
I'm glad you can reply to me. The point I'm referring to is the utilization point. The chain has already been generated, but I don't know if the chain generated by WordPress/RCE2 should be placed in a certain URL or function point on the website to execute this chain for me to complete this test.

**Comment by yuedinga** [comment]
Also, there is WordPress/RCE2, I hope you can help me

**Comment by cfreal** [comment]
You need a plugin that calls `unserialize()` with user supplied data. Please read about `unserialize()` vulnerabilities online.

Closing!
