### ISSUE TITLE
ZendFramework latest version gadget chain

### ISSUE THREAD

**Issue by DanielSparta** [ambionics/phpggc#188]
https://github.com/zendframework/zendframework/releases

![Screenshot from 2024-05-29 08-07-48](https://github.com/ambionics/phpggc/assets/111179755/f52573b5-dc1c-4cf9-9ef8-670bf68c2188)

Right now the newest gadget chain available for zend framework is for the version 2.5.3, while the latest version of zend framework today is 2.4.13 - which published at 2017. Seems like there will be no more versions.

There is a need for adding a gadget chain for the version 2.4.13

![image](https://github.com/ambionics/phpggc/assets/111179755/0cb10a5f-5a4a-4950-a288-3d854639f76f)

**Comment by cfreal** [comment]
Hello Daniel,

I don't understand: 2.4.13 is included in the range 2.0.0 <= 2.5.3, and the RCE5 GC works for this version (I just tested it).
What am I missing?

Charles

**Comment by DanielSparta** [comment]
> Hello Daniel,
> 
> I don't understand: 2.4.13 is included in the range 2.0.0 <= 2.5.3, and the RCE5 GC works for this version (I just tested it). What am I missing?
> 
> Charles

I'm sorry, you right.
Thanks for helping..
Closed
