### ISSUE TITLE
protected properties could be public, simplifying encoding

### ISSUE THREAD

**Issue by mcdruid** [ambionics/phpggc#195]
See https://github.com/ambionics/phpggc/issues/26

In some cases, the way that PHP serializes protected properties means phpggc's output contains NULL bytes which are easy to lose if the payload is transmitted / stored as plain text without encoding.

It looks like it should be possible to change some protected properties to public, thus avoiding the NULL bytes in the payload (added bonus: payloads are marginally smaller).

For example, Drupal7/RCE1 seems to work fine with all of the properties converted to public.

I suppose in some cases the specific target may require that properties remain protected, but is there any reason not to try converting them to public, and suggesting that as a default?

Happy to submit a PR, but wanted to sanity check the idea first.

**Comment by cfreal** [comment]
Hello @mcdruid,

The reason we don't do this is that it does not work with older PHP versions.

See this example code:

```php
<?php

class SomeClass {
    protected $a;

    function getA() {
        return $this->a;
    }
}

$z = unserialize('O:9:"SomeClass":1:{s:1:"a";s:5:"hello";}');
var_dump($z);
var_dump($z->getA());
```

`a` is protected, but through the unserialize call we set it as if it was a public property, as you proposed. Now, see the difference:

```bash
$ php8.1 demo.php
object(SomeClass)#1 (1) {
  ["a":protected]=>
  string(5) "hello"
}
string(5) "hello"
$ php5.6 demo.php
object(SomeClass)#1 (2) {
  ["a":protected]=>
  NULL
  ["a"]=>
  string(5) "hello"
}
NULL
```

Now, we *could* add this behaviour as optional (with something like a `--public-attributes` flag). If you want to PR this, I'll happily add it.

Best,
Charles

**Comment by mcdruid** [comment]
Cool, thanks for the explanation.

I'll have a look at how we'd add an option for public attributes and submit a PR if I can come up with a half-decent approach.

**Comment by mcdruid** [comment]
Submitted a PR with a first pass at adding an `--public-attributes` option.

One thing though.. shouldn't it be `--public-properties`?

**Comment by cfreal** [comment]
I came to the same conclusions as you regarding the feasibility of other solutions. We could do something cleanish where we parse the ast of gadgets.php, but what about PHP-defined classes?  

I was going to comment that there is also `--ascii-strings`, that uses the `S` representation of strings to get rid of binary characters, but it got me wondering how I implemented it. Turns out it bears the same limitations as the code you have PR'ed, @mcdruid.

See https://github.com/ambionics/phpggc/blob/master/lib/PHPGGC/Enhancement/ASCIIStrings.php

Therefore... Well, with a proper warning, your code should be included.

**Comment by mcdruid** [comment]
@cfreal :) I cross posted with you, but we seem to be in general agreement :)

I'd be happy to take at least one more pass at the PR before you final review though if you don't mind.

Apart from anything else I'd like to look at supporting private properties as well as protected.

**Comment by mcdruid** [comment]
I think the PR is ready for review now; it should remove prefixes for private properties as well as protected.

There are warnings in the help text and comments about the circumstances in which the enhancement might not work.

**Comment by mcdruid** [comment]
The PR has been merged. Thanks!
