### ISSUE TITLE
How does the ASCII String feature work?

### ISSUE THREAD

**Issue by Tris0n** [ambionics/phpggc#197]
Hello. During a test in a real scenario, I had problems with passing my payload, as null bytes were being deleted during the HTTP request.

Using the "ASCII Strings" function, the payload worked, as the null bytes were converted to HEX.

I would like to know more about this study. How does "S" work in PHP serialized objects? Where can I study this better? Is there any documentation, or was this discovered by analyzing the PHP core?

**Comment by cfreal** [comment]
Hello @Tris0n,

It apparently got added for "Forward compatibility for PHP 6" on [this commit](https://github.com/php/php-src/commit/8f5310afad0eeef6f2e45a03f6ff7d4a2a7653ce) which dates from Dec 15, 2006. It appeared in PHP 5.2.1.

I don't know (or don't remember) why. If you find anything...

Charles
