### ISSUE TITLE
Add YII framework

### ISSUE THREAD

**Issue by casp3rvpn** [ambionics/phpggc#3]
Do you plan to add YII?

**Comment by cfreal** [comment]
YII seems to use SwiftMailer (Swift-5.4.8 at the time). Did you try the appropriate payload ?

**Comment by casp3rvpn** [comment]
https://github.com/yiisoft/yii
I'm sorry, I'm talking about the latest release of Yii 1.1.x
yii 1:18 (the latest release)

**Comment by cfreal** [comment]
The vector seems fairly easy. I'll implement it next week.

**Comment by casp3rvpn** [comment]
Thank you! Have a nice weekend!

**Comment by cfreal** [comment]
Added.
