### ISSUE TITLE
New line in output breaks signature

### ISSUE THREAD

**Issue by eboda** [ambionics/phpggc#58]
There is a `\n` appended to the output of PHPGGC:
https://github.com/ambionics/phpggc/blob/420c0f17e8d7f02b7709eb2e6ef7706cc0caa379/lib/PHPGGC.php#L89

This is problematic, since it breaks the signature of PHAR archives. 

See the following example:

```bash
$ phpggc -p phar Drupal7/RCE1 var_dump test > /tmp/foo.pdf

$ xxd /tmp/foo.pdf
....
000001e0: 9b22 0200 0000 4742 4d42 0a              ."....GBMB.

$ echo '<?php var_dump(file_exists("phar:///tmp/foo.pdf/test.txt"));'| php 
bool(false)

$ phpggc -p phar Drupal7/RCE1 var_dump test  | head -c -1 > /tmp/foo.pdf

$ xxd /tmp/foo.pdf
....
000001e0: 8f83 0200 0000 4742 4d42                 ......GBMB

$ echo '<?php var_dump(file_exists("phar:///tmp/foo.pdf/test.txt"));'| php 
bool(true)

```

I know there is the `-o` flag to directly write to files, but sometimes you want to pipe the output to base64 or whatever, and in those cases it breaks.

Therefore the `\n` should be completely removed, or at least when used in combination with the `-p` flag. 

Any thoughts?

**Comment by eboda** [comment]
I created a pull request #59 which will only output a newline when `-p` is not used, which in my opinion is a good compromise. What do you think?

**Comment by cfreal** [comment]
Cool. Merged.
