### ISSUE TITLE
There is no gadget found on Windows

### ISSUE THREAD

**Issue by phith0n** [ambionics/phpggc#62]
Because of some bugs, There is no gadget found on Windows:

![image](https://user-images.githubusercontent.com/5711185/62273157-6d527200-b46f-11e9-97cb-d09a613bc058.png)

**Comment by cfreal** [comment]
I went with a patch of my own, using `DIRECTORY_SEPARATOR`. Feels cleaner. Can you test it out ?

**Comment by phith0n** [comment]
Works well, Thanks for responding quickly.
